[package]
name = "weatherbird"
version = "0.5.2"
edition = "2024"
authors = [
    "Cameron Reynolds <cameron@starlordv125.net>",
]
description = "A command line weather program made to set up once and be simple"
homepage = "https://forgejo.starlordv125.net/starlordv125/weatherbird"
include = [
    "src/*.rs",
    "README.md",
    "LICENSE",
]
license = "GPLv3"

[dependencies]
chrono = "0.4.45"
serde = { version = "1.0.228", features = ["derive"] }
toml = "1.1.2"
ureq = { version = "3.3.0", features = ["json"] }

[profile.release]
strip = true  # Automatically strip symbols from the binary.
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"

[package.metadata.generate-rpm]
optional = "true"
release = 3
require-sh = false
assets = [
    { source = "target/release/weatherbird", dest = "/bin/weatherbird", mode = "755" },
    { source = "man/weatherbird.1.gz", dest = "/usr/share/man/man1/weatherbird.1.gz", mode = "755" },
    { source = "bash-completion/weatherbird", dest = "/usr/share/bash-completion/completions/weatherbird", mode = "755" }
]
