[package]
name = "weatherbird"
version = "0.5.2"
edition = "2024"

[dependencies]
chrono = "0.4.45"
serde = { version = "1.0.228", features = ["derive"] }
toml = "1.1.2"
ureq = { version = "3.3.0", features = ["json"] }

[profile.release]
strip = true  # Automatically strip symbols from the binary.
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
