name: RPM-test

on:
  push:
    branches:
      - packaging

jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      VERSION: "0.5.2"
      MESSAGE: "This release adds the option to pick the metric system when using `weatherbird set`. Multiple bugs have been fixed, including fog showing as an unknown weather type."
      RELEASE: 13
      API_KEY: ${{ secrets.FORGEJO_TOKEN }}
      GPG_KEY: ${{ secrets.GPG_KEY }}
      GPG_PASS: ${{ secrets.GPG_PASS }}
    steps:
        - name: Checkout  # Clone git repository
          uses: actions/checkout@v3
        - name: Install Rust toolchain
          uses: https://github.com/dtolnay/rust-toolchain@stable
        - name: Setup
          run: ./scripts/setup.sh
        - name: Build binary
          run: ./scripts/build.sh
        - name: Sign and upload rpm
          run: ./scripts/rpm.sh