name: Rust test

on:
  push:
    branches:
      - actions

#test1
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout  # Clone git repository
          uses: actions/checkout@v3
        - name: Install Rust toolchain
          uses: https://github.com/dtolnay/rust-toolchain@stable
        #- name: Check that code can compile
        #  run: cargo check
        - name: Build Rust binary
          run: cargo build --release
        - name: Create tar archive
          run: |
            mkdir package
            mkdir package/weatherbird-linux-amd64
            cp target/release/weatherbird package/weatherbird-linux-amd64
            cp LICENSE package/weatherbird-linux-amd64
            cp README.md package/weatherbird-linux-amd64
            tar -czvf weatherbird-linux-amd64.tar.zstd package/weatherbird-linux-amd64
        - name: Create release
          run: |
            curl -X 'POST' \
              'https://forgejo.starlordv125.net/api/v1/repos/starlordv125/weatherbird/releases' \
              -H 'accept: application/json' \
              -H 'Authorization: token ${{ secrets.API_KEY }}' \
              -H 'Content-Type: application/json' \
              -d '{
              "body": "Test release!!",
              "draft": false,
              "hide_archive_links": false,
              "name": "test for actions",
              "prerelease": false,
              "tag_name": "v0.4.2",
              "target_commitish": "actions"
            }'
        - name: Upload binary to releases
        # on release 5
          run: |
            curl -X 'POST' \
            'https://forgejo.starlordv125.net/api/v1/repos/starlordv125/weatherbird/releases/5/assets?name=weatherbird-linux-amd64' \
            -H 'accept: application/json' \
            -H 'authorization: token ${{ secrets.API_KEY }}' \
            -H 'Content-Type: multipart/form-data' \
            -F 'attachment=@package/weatherbird-linux-amd64.tar.gz;type=text/x-dsrc'