name: Rust test

on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    env:
    # CHANGE THESE WHEN PUSHING TO MAIN
    # +1 to RELEASE temp
      VERSION: "0.5.1"
      MESSAGE: "This release switches from reqwest, which needed an async runtime to ureq. This decreases the binary size by about two megabytes. This release also handles network connection errors more gracefully."
      RELEASE: 12
    steps:
        - name: Checkout  # Clone git repository
          uses: actions/checkout@v3
        - name: Install Rust toolchain
          uses: https://github.com/dtolnay/rust-toolchain@stable
        - name: Build Rust binary
          run: cargo build --release
        - name: Create tar archive
          run: |
            mkdir package
            mkdir package/weatherbird-linux-amd64
            cp target/release/weatherbird package/weatherbird-linux-amd64
            cp LICENSE package/weatherbird-linux-amd64
            cp README.md package/weatherbird-linux-amd64
            cd package
            tar -czvf ./weatherbird-linux-amd64.tar.gz ./weatherbird-linux-amd64
            cd ../
        - name: Create release
          run: |
            curl -X 'POST' \
              'https://forgejo.starlordv125.net/api/v1/repos/starlordv125/weatherbird/releases' \
              -H 'accept: application/json' \
              -H 'Authorization: token ${{ secrets.API_KEY }}' \
              -H 'Content-Type: application/json' \
              -d '{
              "body": "${{ env.MESSAGE }}",
              "draft": false,
              "hide_archive_links": false,
              "name": "v${{ env.VERSION }}",
              "prerelease": false,
              "tag_name": "v${{ env.VERSION }}",
              "target_commitish": "main"
            }'
        - name: Upload binary package to releases
          run: |
            curl -X 'POST' \
            'https://forgejo.starlordv125.net/api/v1/repos/starlordv125/weatherbird/releases/${{ env.RELEASE }}/assets?name=weatherbird-linux-amd64.tar.gz' \
            -H 'accept: application/json' \
            -H 'authorization: token ${{ secrets.API_KEY }}' \
            -H 'Content-Type: multipart/form-data' \
            -F 'attachment=@./package/weatherbird-linux-amd64.tar.gz;type=text/x-dsrc'
        - name: Update Debian package repository
          run: |
            apt install dpkg -y
            mkdir -p package/deb/weatherbird/DEBIAN/
            mkdir -p package/deb/weatherbird/usr/share/bash-completion/completions/
            touch package/deb/weatherbird/DEBIAN/control
            echo "Source: weatherbird
            Section: main
            Priority: optional
            Maintainer: Cameron Reynolds <cameron@starlordv125.net>
            Homepage: https://forgejo.starlordv125.net/starlordv125/weatherbird
            Package: weatherbird
            Version: ${{ env.VERSION }}-1
            Architecture: amd64
            Depends: 
            Description: A simple weather program written in Rust.
            Distribution: trixie
            Component: main" >> package/deb/weatherbird/DEBIAN/control
            echo '#!/bin/bash

            _Weatherbird() {
            local cur
            cur=${COMP_WORDS[COMP_CWORD]}
            COMPREPLY=( $(compgen -W "set days hours --help --version" -- "$cur") )
            }
            complete -F _Weatherbird weatherbird' >> package/deb/weatherbird/usr/share/bash-completion/completions/weatherbird
            mkdir -p package/deb/weatherbird/usr/bin
            cp target/release/weatherbird package/deb/weatherbird/usr/bin
            cd package/deb
            chmod -R 755 weatherbird
            dpkg-deb --root-owner-group --build weatherbird
            curl --user starlordv125:${{ secrets.API_KEY }} \
            --upload-file ./weatherbird.deb \
            https://forgejo.starlordv125.net/api/packages/starlordv125/debian/pool/trixie/main/upload